Repository fga-eps-mds/2020.2-Anunbis-Frontend, pull requests merged in 2021-05, with the labels that each got.

#20 Criação da tela Home
  app/src/assets/constants/GlobalStyle.js
  app/src/assets/images/Communication.svg
  app/src/assets/images/Eduardo.jpeg
  app/src/assets/images/LogoHome.svg
  app/src/assets/images/Puzzle.svg
  app/src/assets/images/Rafael.jpeg
  app/src/assets/images/Rafael.svg
  app/src/assets/images/Roberto.jpeg
  app/src/assets/images/Rodrigo.jpeg
  app/src/assets/images/Teamwork.svg
  app/src/assets/images/Thiago.jpeg
  app/src/assets/images/Victor.jpeg
  app/src/components/HeadIcon/index.js
  app/src/components/HeadIcon/styles.js
  app/src/components/LayoutApp/index.js
  app/src/components/LayoutApp/styles.js
  app/src/components/Menu/index.js
  app/src/components/Menu/styles.js
  app/src/routes/routes.js
  app/src/services/Auth.js
  app/src/views/Home/index.js
  app/src/views/Home/styles.js
  app/src/views/Profile/index.js
  app/src/views/RegisterProfessor/index.js
  app/src/views/RegisterStudent/index.js
Labels: Developer, enhancement

#21 #135 Tela inicial de aluno
  app/src/components/LayoutApp/index.js
  app/src/components/Menu/index.js
  app/src/components/Post/index.js
  app/src/routes/routes.js
  app/src/services/Auth.js
  app/src/services/Users.js
  app/src/views/Login/index.js
  app/src/views/ProfessorSearch/index.js
  app/src/views/StudentHome/index.js
  app/src/views/StudentHome/styles.js
Labels: Developer, User Story

#29 #132 Opções de ordenação das avaliações
  app/src/components/Feed/index.js
  app/src/components/Feed/styles.js
  app/src/components/Post/index.js
  app/src/components/Select/index.js
  app/src/components/Select/styles.js
  app/src/services/Orders.js
  app/src/views/ProfessorHome/index.js
  app/src/views/StudentHome/index.js
Labels: Developer, User Story

#30 Adicionando Gráfico de desempenho do professor
  app/package-lock.json
  app/package.json
  app/src/components/Menu/styles.js
  app/src/components/Select/index.js
  app/src/components/Select/styles.js
  app/src/components/Statistics/index.js
  app/src/components/Statistics/styles.js
  app/src/views/ProfessorHome/index.js
  app/src/views/ProfessorSearch/index.js
  app/src/views/StudentHome/index.js
Labels: Developer, enhancement

#34 #221 carregamento onclick dos buttons
  app/package-lock.json
  app/package.json
  app/src/components/Avaliation/index.js
  app/src/components/Avaliation/styles.js
  app/src/components/ExcludeAccount/index.js
  app/src/components/ExcludeAccount/styles.js
  app/src/components/LayoutApp/index.js
  app/src/components/Loading/index.js
  app/src/components/Loading/styles.js
  app/src/components/Login/index.js
  app/src/components/RegisterProfessor/index.js
  app/src/components/RegisterStudent/index.js
  app/src/components/Report/index.js
  app/src/components/Report/validations.js
  app/src/components/ResetPassword/index.js
  app/src/components/ResetPassword/styles.js
  app/src/tests/componentsTests/Login.test.js
  app/src/tests/componentsTests/RegisterProfessor.test.js
  app/src/tests/componentsTests/RegisterStudent.test.js
  app/src/tests/componentsTests/__snapshots__/Avaliation.test.js.snap
  app/src/tests/componentsTests/__snapshots__/Loading.test.js.snap
  app/src/tests/componentsTests/__snapshots__/Report.test.js.snap
  app/src/tests/routesTests/__snapshots__/routes.test.js.snap
  app/src/tests/viewsTests/__snapshots__/Authentication.test.js.snap
  app/src/tests/viewsTests/__snapshots__/Profile.test.js.snap
  app/src/views/Authentication/index.js
  app/src/views/Authentication/styles.js
  app/src/views/ProfessorSearch/index.js
  app/src/views/Profile/index.js
Labels: bug
