Repository fga-eps-mds/2020.2-Anunbis-Frontend, pull requests merged in 2021-04, with the labels that each got.

#11 #122 Trocando o css por styled components
  package-lock.json
  package.json
  public/index.html
  src/components/Avaliation/index.css
  src/components/Avaliation/index.js
  src/components/Button/index.css
  src/components/Button/index.js
  src/components/Feed/index.css
  src/components/Feed/index.js
  src/components/Form/index.css
  src/components/Form/index.js
  src/components/Input/index.css
  src/components/Input/index.js
  src/components/LayoutApp/index.css
  src/components/LayoutApp/index.js
  src/components/LayoutAutentication/index.js
  src/components/Menu/index.css
  src/components/Menu/index.js
  src/components/Post/index.css
  src/components/Post/index.js
  src/components/ProfessorBox/index.css
  src/components/ProfessorBox/index.js
  src/components/Select/index.js
  src/routes.js
  src/views/Application/index.css
  src/views/Application/index.js
  src/views/Login/index.css
  src/views/Login/index.js
  src/views/ProfessorSearch/index.css
  src/views/ProfessorSearch/index.js
  src/views/RegisterProfessor/index.css
  src/views/RegisterProfessor/index.js
  src/views/RegisterStudent/index.css
  src/views/RegisterStudent/index.js
Labels: Developer

#12 Bugfix/#150 Resolvendo bug do Login
  src/services/authentication/index.js
  src/views/Login/index.js
Labels: Developer, bug

#13 Autenticando as rotas com Axios
  package-lock.json
  package.json
  src/components/Avaliation/index.js
  src/components/Select/index.js
  src/routes.js
  src/services/Api.js
  src/services/Auth.js
  src/services/authentication/index.js
  src/views/Login/index.js
  src/views/ProfessorSearch/index.js
  src/views/RegisterProfessor/index.js
  src/views/RegisterStudent/index.js
Labels: Developer, enhancement

#15 #138 [US20] [US21] Denuncia de Avaliação
  src/assets/Report_Icon_BW.png
  src/assets/Report_Icon_C.png
  src/components/Avaliation/index.js
  src/components/Button/index.js
  src/components/Checkbox/index.js
  src/components/FeedPopup/index.js
  src/components/Post/index.js
  src/components/ProfessorBox/index.js
  src/components/Report/index.js
  src/components/Report/validations.js
  src/views/ProfessorSearch/index.js
Labels: Developer, User Story, enhancement

#17 #137 [US19] Botoes de concordo e discordo
  app/src/assets/images/Agreed_Icon_BW.png
  app/src/assets/images/Agreed_Icon_C.png
  app/src/assets/images/Disagreed_Icon_BW.png
  app/src/assets/images/Disagreed_Icon_C.png
  app/src/components/Button/index.js
  app/src/components/Button/styles.js
  app/src/components/Menu/index.js
  app/src/components/Post/index.js
  app/src/components/Post/styles.js
  app/src/components/ProfessorBox/index.js
  app/src/components/ProfessorBox/styles.js
  app/src/components/Report/index.js
  app/src/components/ResetPassword/index.js
  app/src/components/Select/index.js
Labels: Developer, User Story
